version: 2
jobs:
  build_django:
    working_directory: ~/budgetManager
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd ~/budgetManager/backend
            pipenv install
      - run:
          name: Run unit tests
          command: |
            cd ~/budgetManager/backend
            pipenv run python manage.py test
  build_vue:
    working_directory: ~/budgetManager
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd ~/budgetManager/frontend
            npm install
      - run:
          name: Run build
          command: |
            cd ~/budgetManager/frontend
            npm run build
      - add_ssh_keys
      - deploy:
          name: Deploy to VPS
          command: |
            ssh-keyscan 159.89.7.48 >> ~/.ssh/known_hosts
            cd ~/budgetManager/frontend
            sudo apt install rsync
            rsync -va --delete dist/ lukas@159.89.7.48:/home/lukas/test/
workflows:
  version: 2
  my_workflow: 
    jobs:
      - build_django
      - build_vue