version: 2
jobs:
  build:
    working_directory: ~/budgetManager
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd ~/budgetManager/backend
            pipenv install
      - run:
          name: Run unit tests
          command: |
            cd ~/budgetManager/backend
            pipenv run python manage.py test
      - store_artifacts:
          path: test-reports
          destination: test-reports