version: 2
jobs:
  build:
    working_directory: ~/budgetManager/backend/
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          name: Run unit tests
          command: |
            pipenv shell
            python manage.py test
      - store_artifacts:
          path: test-reports
          destination: test-reports