# Generated by Django 2.0.3 on 2018-03-27 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=32, verbose_name='Transaction type')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Amount')),
                ('date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.Category', verbose_name='Category')),
            ],
        ),
    ]
