# Generated by Django 2.0.3 on 2018-04-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20180402_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='categories',
            field=models.ManyToManyField(blank=True, to='transactions.Category'),
        ),
    ]
