# Generated by Django 2.0.3 on 2018-04-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20180402_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Balance'),
            preserve_default=False,
        ),
    ]
