# Generated by Django 2.0.3 on 2018-04-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20180402_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Balance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='transactions.Wallet', verbose_name='Wallet'),
        ),
    ]
