# Generated by Django 2.0.3 on 2018-04-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20180402_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
