# Generated by Django 2.0.3 on 2018-04-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_remove_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Balance'),
        ),
    ]
