# Generated by Django 2.0.3 on 2018-04-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20180402_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.Wallet', verbose_name='Wallet'),
            preserve_default=False,
        ),
    ]
