# Generated by Django 2.0.3 on 2018-04-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_auto_20180419_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='categories',
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='transactions.Category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='transactions.Wallet', verbose_name='Wallet'),
        ),
    ]
