# Generated by Django 2.0.3 on 2018-05-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20180423_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=32, verbose_name='Period'),
        ),
    ]
