# Generated by Django 2.0.3 on 2018-04-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='status',
        ),
        migrations.AddField(
            model_name='invitation',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
